# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_de_juego.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(467, 780)
        MainWindow.setStyleSheet("background-color: rgb(23, 21, 35);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fondo = QtWidgets.QLabel(self.centralwidget)
        self.fondo.setGeometry(QtCore.QRect(40, 160, 391, 561))
        self.fondo.setStyleSheet("background-color: rgb(26, 26, 26);")
        self.fondo.setObjectName("fondo")
        self.borde_1 = QtWidgets.QLabel(self.centralwidget)
        self.borde_1.setGeometry(QtCore.QRect(20, 140, 21, 581))
        self.borde_1.setStyleSheet("background-color: rgb(169, 171, 171);")
        self.borde_1.setObjectName("borde_1")
        self.borde_2 = QtWidgets.QLabel(self.centralwidget)
        self.borde_2.setGeometry(QtCore.QRect(430, 140, 21, 581))
        self.borde_2.setStyleSheet("background-color: rgb(169, 171, 171);")
        self.borde_2.setObjectName("borde_2")
        self.borde_3 = QtWidgets.QLabel(self.centralwidget)
        self.borde_3.setGeometry(QtCore.QRect(20, 140, 431, 21))
        self.borde_3.setStyleSheet("background-color: rgb(169, 171, 171);")
        self.borde_3.setObjectName("borde_3")
        self.borde_4 = QtWidgets.QLabel(self.centralwidget)
        self.borde_4.setGeometry(QtCore.QRect(20, 700, 431, 21))
        self.borde_4.setStyleSheet("background-color: rgb(169, 171, 171);")
        self.borde_4.setObjectName("borde_4")
        self.logo_DCCTetis = QtWidgets.QLabel(self.centralwidget)
        self.logo_DCCTetis.setGeometry(QtCore.QRect(20, 10, 141, 111))
        self.logo_DCCTetis.setStyleSheet("font: 24pt \"Lucida Grande\";\n"
"color: rgb(255, 255, 255);")
        self.logo_DCCTetis.setObjectName("logo_DCCTetis")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(180, 10, 261, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nombre = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.nombre.setStyleSheet("font: 17pt \"Lucida Grande\";\n"
"color: rgb(255, 255, 255);")
        self.nombre.setObjectName("nombre")
        self.horizontalLayout.addWidget(self.nombre)
        self.nombre_usuario = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.nombre_usuario.setStyleSheet("font: 17pt \"Lucida Grande\";\n"
"color: rgb(255, 255, 255);")
        self.nombre_usuario.setObjectName("nombre_usuario")
        self.horizontalLayout.addWidget(self.nombre_usuario)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(180, 50, 261, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.nombre_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.nombre_3.setStyleSheet("font: 17pt \"Lucida Grande\";\n"
"color: rgb(255, 255, 255);")
        self.nombre_3.setObjectName("nombre_3")
        self.horizontalLayout_3.addWidget(self.nombre_3)
        self.puntaje_usuario = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.puntaje_usuario.setStyleSheet("font: 17pt \"Lucida Grande\";\n"
"color: rgb(255, 255, 255);")
        self.puntaje_usuario.setObjectName("puntaje_usuario")
        self.horizontalLayout_3.addWidget(self.puntaje_usuario)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(180, 90, 261, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.nombre_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.nombre_4.setStyleSheet("font: 17pt \"Lucida Grande\";\n"
"color: rgb(255, 255, 255);")
        self.nombre_4.setObjectName("nombre_4")
        self.horizontalLayout_4.addWidget(self.nombre_4)

"color: rgb(255, 255, 255);")
        self.puntaje_mas_alto.setObjectName("puntaje_mas_alto")
        self.horizontalLayout_4.addWidget(self.puntaje_mas_alto)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 160, 391, 541))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.grilla_3_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_3_6.setStyleSheet("")
        self.grilla_3_6.setObjectName("grilla_3_6")
        self.gridLayout.addWidget(self.grilla_3_6, 16, 6, 1, 1)
        self.grilla_7_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_7_6.setStyleSheet("")
        self.grilla_7_6.setObjectName("grilla_7_6")
        self.gridLayout.addWidget(self.grilla_7_6, 12, 6, 1, 1)
        self.grilla_6_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_6_6.setStyleSheet("")
        self.grilla_6_6.setObjectName("grilla_6_6")
        self.gridLayout.addWidget(self.grilla_6_6, 13, 6, 1, 1)
        self.grilla_2_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_2_4.setStyleSheet("")
        self.grilla_2_4.setObjectName("grilla_2_4")
        self.gridLayout.addWidget(self.grilla_2_4, 17, 4, 1, 1)
        self.grilla_4_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_4_4.setStyleSheet("")
        self.grilla_4_4.setObjectName("grilla_4_4")
        self.gridLayout.addWidget(self.grilla_4_4, 15, 4, 1, 1)
        self.grilla_6_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_6_4.setStyleSheet("")
        self.grilla_6_4.setObjectName("grilla_6_4")
        self.gridLayout.addWidget(self.grilla_6_4, 13, 4, 1, 1)
        self.grilla_7_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_7_4.setStyleSheet("")
        self.grilla_7_4.setObjectName("grilla_7_4")
        self.gridLayout.addWidget(self.grilla_7_4, 12, 4, 1, 1)
        self.grilla_3_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_3_4.setStyleSheet("")
        self.grilla_3_4.setObjectName("grilla_3_4")
        self.gridLayout.addWidget(self.grilla_3_4, 16, 4, 1, 1)
        self.grilla_5_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_5_8.setStyleSheet("")
        self.grilla_5_8.setObjectName("grilla_5_8")
        self.gridLayout.addWidget(self.grilla_5_8, 14, 8, 1, 1)
        self.grilla_9_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_9_8.setStyleSheet("")
        self.grilla_9_8.setObjectName("grilla_9_8")
        self.gridLayout.addWidget(self.grilla_9_8, 10, 8, 1, 1)
        self.grilla_9_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_9_2.setStyleSheet("")
        self.grilla_9_2.setObjectName("grilla_9_2")
        self.gridLayout.addWidget(self.grilla_9_2, 10, 2, 1, 1)
        self.grilla_13_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_13_9.setStyleSheet("")
        self.grilla_13_9.setObjectName("grilla_13_9")
        self.gridLayout.addWidget(self.grilla_13_9, 6, 9, 1, 1)
        self.grilla_3_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_3_8.setStyleSheet("")
        self.grilla_3_8.setObjectName("grilla_3_8")
        self.gridLayout.addWidget(self.grilla_3_8, 16, 8, 1, 1)
        self.grilla_8_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_8_8.setStyleSheet("")
        self.grilla_8_8.setObjectName("grilla_8_8")
        self.gridLayout.addWidget(self.grilla_8_8, 11, 8, 1, 1)
        self.grilla_1_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_1_8.setStyleSheet("")
        self.grilla_1_8.setObjectName("grilla_1_8")
        self.gridLayout.addWidget(self.grilla_1_8, 18, 8, 1, 1)
        self.grilla_1_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_1_5.setStyleSheet("")
        self.grilla_1_5.setObjectName("grilla_1_5")
        self.gridLayout.addWidget(self.grilla_1_5, 18, 5, 1, 1)
        self.grilla_4_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_4_2.setStyleSheet("")
        self.grilla_4_2.setObjectName("grilla_4_2")
        self.gridLayout.addWidget(self.grilla_4_2, 15, 2, 1, 1)
        self.grilla_0_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_0_8.setStyleSheet("")
        self.grilla_0_8.setObjectName("grilla_0_8")
        self.gridLayout.addWidget(self.grilla_0_8, 19, 8, 1, 1)
        self.grilla_10_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_10_7.setStyleSheet("")
        self.grilla_10_7.setObjectName("grilla_10_7")
        self.gridLayout.addWidget(self.grilla_10_7, 9, 7, 1, 1)
        self.grilla_7_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_7_8.setStyleSheet("")
        self.grilla_7_8.setObjectName("grilla_7_8")
        self.gridLayout.addWidget(self.grilla_7_8, 12, 8, 1, 1)
        self.grilla_1_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_1_1.setStyleSheet("")
        self.grilla_1_1.setObjectName("grilla_1_1")
        self.gridLayout.addWidget(self.grilla_1_1, 18, 1, 1, 1)
        self.grilla_0_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_0_1.setStyleSheet("")
        self.grilla_0_1.setObjectName("grilla_0_1")
        self.gridLayout.addWidget(self.grilla_0_1, 19, 1, 1, 1)
        self.grilla_6_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_6_5.setStyleSheet("")
        self.grilla_6_5.setObjectName("grilla_6_5")
        self.gridLayout.addWidget(self.grilla_6_5, 13, 5, 1, 1)
        self.grilla_14_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_14_7.setStyleSheet("")
        self.grilla_14_7.setObjectName("grilla_14_7")
        self.gridLayout.addWidget(self.grilla_14_7, 5, 7, 1, 1)
        self.grilla_14_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_14_9.setStyleSheet("")
        self.grilla_14_9.setObjectName("grilla_14_9")
        self.gridLayout.addWidget(self.grilla_14_9, 5, 9, 1, 1)
        self.grilla_17_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_17_0.setStyleSheet("")
        self.grilla_17_0.setObjectName("grilla_17_0")
        self.gridLayout.addWidget(self.grilla_17_0, 2, 0, 1, 1)
        self.grilla_8_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_8_0.setStyleSheet("")
        self.grilla_8_0.setObjectName("grilla_8_0")
        self.gridLayout.addWidget(self.grilla_8_0, 11, 0, 1, 1)
        self.grilla_13_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_13_2.setStyleSheet("")
        self.grilla_13_2.setObjectName("grilla_13_2")
        self.gridLayout.addWidget(self.grilla_13_2, 6, 2, 1, 1)
        self.grilla_8_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_8_7.setStyleSheet("")
        self.grilla_8_7.setObjectName("grilla_8_7")
        self.gridLayout.addWidget(self.grilla_8_7, 11, 7, 1, 1)
        self.grilla_11_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_11_4.setStyleSheet("")
        self.grilla_11_4.setObjectName("grilla_11_4")
        self.gridLayout.addWidget(self.grilla_11_4, 8, 4, 1, 1)
        self.grilla_18_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_18_6.setStyleSheet("")
        self.grilla_18_6.setObjectName("grilla_18_6")
        self.gridLayout.addWidget(self.grilla_18_6, 1, 6, 1, 1)
        self.grilla_11_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_11_2.setStyleSheet("")
        self.grilla_11_2.setObjectName("grilla_11_2")
        self.gridLayout.addWidget(self.grilla_11_2, 8, 2, 1, 1)
        self.grilla_14_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_14_5.setStyleSheet("")
        self.grilla_14_5.setObjectName("grilla_14_5")
        self.gridLayout.addWidget(self.grilla_14_5, 5, 5, 1, 1)
        self.grilla_16_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_16_0.setStyleSheet("")
        self.grilla_16_0.setObjectName("grilla_16_0")
        self.gridLayout.addWidget(self.grilla_16_0, 3, 0, 1, 1)
        self.grilla_12_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_12_1.setStyleSheet("")
        self.grilla_12_1.setObjectName("grilla_12_1")
        self.gridLayout.addWidget(self.grilla_12_1, 7, 1, 1, 1)
        self.grilla_11_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_11_3.setStyleSheet("")
        self.grilla_11_3.setObjectName("grilla_11_3")
        self.gridLayout.addWidget(self.grilla_11_3, 8, 3, 1, 1)
        self.grilla_18_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_18_9.setStyleSheet("")
        self.grilla_18_9.setObjectName("grilla_18_9")
        self.gridLayout.addWidget(self.grilla_18_9, 1, 9, 1, 1)
        self.grilla_16_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_16_6.setStyleSheet("")
        self.grilla_16_6.setObjectName("grilla_16_6")
        self.gridLayout.addWidget(self.grilla_16_6, 3, 6, 1, 1)
        self.grilla_9_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_9_4.setStyleSheet("")
        self.grilla_9_4.setObjectName("grilla_9_4")
        self.gridLayout.addWidget(self.grilla_9_4, 10, 4, 1, 1)
        self.grilla_12_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_12_2.setStyleSheet("")
        self.grilla_12_2.setObjectName("grilla_12_2")
        self.gridLayout.addWidget(self.grilla_12_2, 7, 2, 1, 1)
        self.grilla_6_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_6_1.setStyleSheet("")
        self.grilla_6_1.setObjectName("grilla_6_1")
        self.gridLayout.addWidget(self.grilla_6_1, 13, 1, 1, 1)
        self.grilla_15_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_15_4.setStyleSheet("")
        self.grilla_15_4.setObjectName("grilla_15_4")
        self.gridLayout.addWidget(self.grilla_15_4, 4, 4, 1, 1)
        self.grilla_12_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_12_3.setStyleSheet("")
        self.grilla_12_3.setObjectName("grilla_12_3")
        self.gridLayout.addWidget(self.grilla_12_3, 7, 3, 1, 1)
        self.grilla_10_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_10_1.setStyleSheet("")
        self.grilla_10_1.setObjectName("grilla_10_1")
        self.gridLayout.addWidget(self.grilla_10_1, 9, 1, 1, 1)
        self.grilla_7_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_7_1.setStyleSheet("")
        self.grilla_7_1.setObjectName("grilla_7_1")
        self.gridLayout.addWidget(self.grilla_7_1, 12, 1, 1, 1)
        self.grilla_8_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_8_1.setStyleSheet("")
        self.grilla_8_1.setObjectName("grilla_8_1")
        self.gridLayout.addWidget(self.grilla_8_1, 11, 1, 1, 1)
        self.grilla_5_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_5_1.setStyleSheet("")
        self.grilla_5_1.setObjectName("grilla_5_1")
        self.gridLayout.addWidget(self.grilla_5_1, 14, 1, 1, 1)
        self.grilla_8_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_8_6.setStyleSheet("")
        self.grilla_8_6.setObjectName("grilla_8_6")
        self.gridLayout.addWidget(self.grilla_8_6, 11, 6, 1, 1)
        self.grilla_9_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_9_1.setStyleSheet("")
        self.grilla_9_1.setObjectName("grilla_9_1")
        self.gridLayout.addWidget(self.grilla_9_1, 10, 1, 1, 1)
        self.grilla_15_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_15_3.setStyleSheet("")
        self.grilla_15_3.setObjectName("grilla_15_3")
        self.gridLayout.addWidget(self.grilla_15_3, 4, 3, 1, 1)
        self.grilla_3_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_3_1.setStyleSheet("")
        self.grilla_3_1.setObjectName("grilla_3_1")
        self.gridLayout.addWidget(self.grilla_3_1, 16, 1, 1, 1)
        self.grilla_2_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_2_1.setStyleSheet("")
        self.grilla_2_1.setObjectName("grilla_2_1")
        self.gridLayout.addWidget(self.grilla_2_1, 17, 1, 1, 1)
        self.grilla_9_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_9_7.setStyleSheet("")
        self.grilla_9_7.setObjectName("grilla_9_7")
        self.gridLayout.addWidget(self.grilla_9_7, 10, 7, 1, 1)
        self.grilla_7_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_7_5.setStyleSheet("")
        self.grilla_7_5.setObjectName("grilla_7_5")
        self.gridLayout.addWidget(self.grilla_7_5, 12, 5, 1, 1)
        self.grilla_0_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_0_6.setStyleSheet("")
        self.grilla_0_6.setObjectName("grilla_0_6")
        self.gridLayout.addWidget(self.grilla_0_6, 19, 6, 1, 1)
        self.grilla_10_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_10_5.setStyleSheet("")
        self.grilla_10_5.setObjectName("grilla_10_5")
        self.gridLayout.addWidget(self.grilla_10_5, 9, 5, 1, 1)
        self.grilla_4_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_4_8.setStyleSheet("")
        self.grilla_4_8.setObjectName("grilla_4_8")
        self.gridLayout.addWidget(self.grilla_4_8, 15, 8, 1, 1)
        self.grilla_6_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_6_8.setStyleSheet("")
        self.grilla_6_8.setObjectName("grilla_6_8")
        self.gridLayout.addWidget(self.grilla_6_8, 13, 8, 1, 1)
        self.grilla_5_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_5_5.setStyleSheet("")
        self.grilla_5_5.setObjectName("grilla_5_5")
        self.gridLayout.addWidget(self.grilla_5_5, 14, 5, 1, 1)
        self.grilla_2_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_2_2.setStyleSheet("")
        self.grilla_2_2.setObjectName("grilla_2_2")
        self.gridLayout.addWidget(self.grilla_2_2, 17, 2, 1, 1)
        self.grilla_3_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_3_2.setStyleSheet("")
        self.grilla_3_2.setObjectName("grilla_3_2")
        self.gridLayout.addWidget(self.grilla_3_2, 16, 2, 1, 1)
        self.grilla_8_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_8_4.setStyleSheet("")
        self.grilla_8_4.setObjectName("grilla_8_4")
        self.gridLayout.addWidget(self.grilla_8_4, 11, 4, 1, 1)
        self.grilla_6_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_6_2.setStyleSheet("")
        self.grilla_6_2.setObjectName("grilla_6_2")
        self.gridLayout.addWidget(self.grilla_6_2, 13, 2, 1, 1)
        self.grilla_5_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_5_7.setStyleSheet("")
        self.grilla_5_7.setObjectName("grilla_5_7")
        self.gridLayout.addWidget(self.grilla_5_7, 14, 7, 1, 1)
        self.grilla_2_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_2_6.setStyleSheet("")
        self.grilla_2_6.setObjectName("grilla_2_6")
        self.gridLayout.addWidget(self.grilla_2_6, 17, 6, 1, 1)
        self.grilla_8_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_8_2.setStyleSheet("")
        self.grilla_8_2.setObjectName("grilla_8_2")
        self.gridLayout.addWidget(self.grilla_8_2, 11, 2, 1, 1)
        self.grilla_2_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_2_7.setStyleSheet("")
        self.grilla_2_7.setObjectName("grilla_2_7")
        self.gridLayout.addWidget(self.grilla_2_7, 17, 7, 1, 1)
        self.grilla_9_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_9_6.setStyleSheet("")
        self.grilla_9_6.setObjectName("grilla_9_6")
        self.gridLayout.addWidget(self.grilla_9_6, 10, 6, 1, 1)
        self.grilla_3_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_3_7.setStyleSheet("")
        self.grilla_3_7.setObjectName("grilla_3_7")
        self.gridLayout.addWidget(self.grilla_3_7, 16, 7, 1, 1)
        self.grilla_7_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_7_7.setStyleSheet("")
        self.grilla_7_7.setObjectName("grilla_7_7")
        self.gridLayout.addWidget(self.grilla_7_7, 12, 7, 1, 1)
        self.grilla_1_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_1_7.setStyleSheet("")
        self.grilla_1_7.setObjectName("grilla_1_7")
        self.gridLayout.addWidget(self.grilla_1_7, 18, 7, 1, 1)
        self.grilla_5_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_5_6.setStyleSheet("")
        self.grilla_5_6.setObjectName("grilla_5_6")
        self.gridLayout.addWidget(self.grilla_5_6, 14, 6, 1, 1)
        self.grilla_15_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_15_2.setStyleSheet("")
        self.grilla_15_2.setObjectName("grilla_15_2")
        self.gridLayout.addWidget(self.grilla_15_2, 4, 2, 1, 1)
        self.grilla_10_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_10_2.setStyleSheet("")
        self.grilla_10_2.setObjectName("grilla_10_2")
        self.gridLayout.addWidget(self.grilla_10_2, 9, 2, 1, 1)
        self.grilla_4_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_4_5.setStyleSheet("")
        self.grilla_4_5.setObjectName("grilla_4_5")
        self.gridLayout.addWidget(self.grilla_4_5, 15, 5, 1, 1)
        self.grilla_10_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_10_6.setStyleSheet("")
        self.grilla_10_6.setObjectName("grilla_10_6")
        self.gridLayout.addWidget(self.grilla_10_6, 9, 6, 1, 1)
        self.grilla_4_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_4_6.setStyleSheet("")
        self.grilla_4_6.setObjectName("grilla_4_6")
        self.gridLayout.addWidget(self.grilla_4_6, 15, 6, 1, 1)
        self.grilla_2_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_2_8.setStyleSheet("")
        self.grilla_2_8.setObjectName("grilla_2_8")
        self.gridLayout.addWidget(self.grilla_2_8, 17, 8, 1, 1)
        self.grilla_2_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_2_5.setStyleSheet("")
        self.grilla_2_5.setObjectName("grilla_2_5")
        self.gridLayout.addWidget(self.grilla_2_5, 17, 5, 1, 1)
        self.grilla_3_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_3_5.setStyleSheet("")
        self.grilla_3_5.setObjectName("grilla_3_5")
        self.gridLayout.addWidget(self.grilla_3_5, 16, 5, 1, 1)
        self.grilla_5_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_5_2.setStyleSheet("")
        self.grilla_5_2.setObjectName("grilla_5_2")
        self.gridLayout.addWidget(self.grilla_5_2, 14, 2, 1, 1)
        self.grilla_9_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_9_5.setStyleSheet("")
        self.grilla_9_5.setObjectName("grilla_9_5")
        self.gridLayout.addWidget(self.grilla_9_5, 10, 5, 1, 1)
        self.grilla_0_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_0_7.setStyleSheet("")
        self.grilla_0_7.setObjectName("grilla_0_7")
        self.gridLayout.addWidget(self.grilla_0_7, 19, 7, 1, 1)
        self.grilla_4_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_4_3.setStyleSheet("")
        self.grilla_4_3.setObjectName("grilla_4_3")
        self.gridLayout.addWidget(self.grilla_4_3, 15, 3, 1, 1)
        self.grilla_8_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_8_3.setStyleSheet("")
        self.grilla_8_3.setObjectName("grilla_8_3")
        self.gridLayout.addWidget(self.grilla_8_3, 11, 3, 1, 1)
        self.grilla_1_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_1_2.setStyleSheet("")
        self.grilla_1_2.setObjectName("grilla_1_2")
        self.gridLayout.addWidget(self.grilla_1_2, 18, 2, 1, 1)
        self.grilla_6_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_6_7.setStyleSheet("")
        self.grilla_6_7.setObjectName("grilla_6_7")
        self.gridLayout.addWidget(self.grilla_6_7, 13, 7, 1, 1)
        self.grilla_7_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_7_2.setStyleSheet("")
        self.grilla_7_2.setObjectName("grilla_7_2")
        self.gridLayout.addWidget(self.grilla_7_2, 12, 2, 1, 1)
        self.grilla_10_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_10_3.setStyleSheet("")
        self.grilla_10_3.setObjectName("grilla_10_3")
        self.gridLayout.addWidget(self.grilla_10_3, 9, 3, 1, 1)
        self.grilla_13_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_13_4.setStyleSheet("")
        self.grilla_13_4.setObjectName("grilla_13_4")
        self.gridLayout.addWidget(self.grilla_13_4, 6, 4, 1, 1)
        self.grilla_4_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_4_7.setStyleSheet("")
        self.grilla_4_7.setObjectName("grilla_4_7")
        self.gridLayout.addWidget(self.grilla_4_7, 15, 7, 1, 1)
        self.grilla_13_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_13_5.setStyleSheet("")
        self.grilla_13_5.setObjectName("grilla_13_5")
        self.gridLayout.addWidget(self.grilla_13_5, 6, 5, 1, 1)
        self.grilla_12_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_12_6.setStyleSheet("")
        self.grilla_12_6.setObjectName("grilla_12_6")
        self.gridLayout.addWidget(self.grilla_12_6, 7, 6, 1, 1)
        self.grilla_14_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_14_6.setStyleSheet("grilla_14_1")
        self.grilla_14_6.setObjectName("grilla_14_6")
        self.gridLayout.addWidget(self.grilla_14_6, 5, 6, 1, 1)
        self.grilla_14_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_14_3.setStyleSheet("")
        self.grilla_14_3.setObjectName("grilla_14_3")
        self.gridLayout.addWidget(self.grilla_14_3, 5, 3, 1, 1)
        self.grilla_17_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_17_2.setStyleSheet("")
        self.grilla_17_2.setObjectName("grilla_17_2")
        self.gridLayout.addWidget(self.grilla_17_2, 2, 2, 1, 1)
        self.grilla_17_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_17_6.setStyleSheet("")
        self.grilla_17_6.setObjectName("grilla_17_6")
        self.gridLayout.addWidget(self.grilla_17_6, 2, 6, 1, 1)
        self.grilla_16_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_16_1.setStyleSheet("")
        self.grilla_16_1.setObjectName("grilla_16_1")
        self.gridLayout.addWidget(self.grilla_16_1, 3, 1, 1, 1)
        self.grilla_15_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_15_5.setStyleSheet("")
        self.grilla_15_5.setObjectName("grilla_15_5")
        self.gridLayout.addWidget(self.grilla_15_5, 4, 5, 1, 1)
        self.grilla_15_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_15_7.setStyleSheet("")
        self.grilla_15_7.setObjectName("grilla_15_7")
        self.gridLayout.addWidget(self.grilla_15_7, 4, 7, 1, 1)
        self.grilla_14_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_14_1.setStyleSheet("")
        self.grilla_14_1.setObjectName("grilla_14_1")
        self.gridLayout.addWidget(self.grilla_14_1, 5, 1, 1, 1)
        self.grilla_14_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_14_0.setStyleSheet("")
        self.grilla_14_0.setObjectName("grilla_14_0")
        self.gridLayout.addWidget(self.grilla_14_0, 5, 0, 1, 1)
        self.grilla_18_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_18_4.setStyleSheet("")
        self.grilla_18_4.setObjectName("grilla_18_4")
        self.gridLayout.addWidget(self.grilla_18_4, 1, 4, 1, 1)
        self.grilla_11_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_11_6.setStyleSheet("")
        self.grilla_11_6.setObjectName("grilla_11_6")
        self.gridLayout.addWidget(self.grilla_11_6, 8, 6, 1, 1)
        self.grilla_17_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_17_9.setStyleSheet("")
        self.grilla_17_9.setObjectName("grilla_17_9")
        self.gridLayout.addWidget(self.grilla_17_9, 2, 9, 1, 1)
        self.grilla_16_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_16_7.setStyleSheet("")
        self.grilla_16_7.setObjectName("grilla_16_7")
        self.gridLayout.addWidget(self.grilla_16_7, 3, 7, 1, 1)
        self.grilla_16_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_16_9.setStyleSheet("")
        self.grilla_16_9.setObjectName("grilla_16_9")
        self.gridLayout.addWidget(self.grilla_16_9, 3, 9, 1, 1)
        self.grilla_1_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_1_6.setStyleSheet("")
        self.grilla_1_6.setObjectName("grilla_1_6")
        self.gridLayout.addWidget(self.grilla_1_6, 18, 6, 1, 1)
        self.grilla_15_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_15_6.setStyleSheet("")
        self.grilla_15_6.setObjectName("grilla_15_6")
        self.gridLayout.addWidget(self.grilla_15_6, 4, 6, 1, 1)
        self.grilla_8_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_8_5.setStyleSheet("")
        self.grilla_8_5.setObjectName("grilla_8_5")
        self.gridLayout.addWidget(self.grilla_8_5, 11, 5, 1, 1)
        self.grilla_17_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_17_5.setStyleSheet("")
        self.grilla_17_5.setObjectName("grilla_17_5")
        self.gridLayout.addWidget(self.grilla_17_5, 2, 5, 1, 1)
        self.grilla_5_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_5_4.setStyleSheet("")
        self.grilla_5_4.setObjectName("grilla_5_4")
        self.gridLayout.addWidget(self.grilla_5_4, 14, 4, 1, 1)
        self.grilla_18_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_18_8.setStyleSheet("")
        self.grilla_18_8.setObjectName("grilla_18_8")
        self.gridLayout.addWidget(self.grilla_18_8, 1, 8, 1, 1)
        self.grilla_11_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_11_9.setStyleSheet("")
        self.grilla_11_9.setObjectName("grilla_11_9")
        self.gridLayout.addWidget(self.grilla_11_9, 8, 9, 1, 1)
        self.grilla_15_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_15_9.setStyleSheet("")
        self.grilla_15_9.setObjectName("grilla_15_9")
        self.gridLayout.addWidget(self.grilla_15_9, 4, 9, 1, 1)
        self.grilla_19_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_19_2.setStyleSheet("")
        self.grilla_19_2.setObjectName("grilla_19_2")
        self.gridLayout.addWidget(self.grilla_19_2, 0, 2, 1, 1)
        self.grilla_0_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_0_2.setStyleSheet("")
        self.grilla_0_2.setObjectName("grilla_0_2")
        self.gridLayout.addWidget(self.grilla_0_2, 19, 2, 1, 1)
        self.grilla_1_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_1_4.setStyleSheet("")
        self.grilla_1_4.setObjectName("grilla_1_4")
        self.gridLayout.addWidget(self.grilla_1_4, 18, 4, 1, 1)
        self.grilla_14_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_14_2.setStyleSheet("")
        self.grilla_14_2.setObjectName("grilla_14_2")
        self.gridLayout.addWidget(self.grilla_14_2, 5, 2, 1, 1)
        self.grilla_19_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_19_5.setStyleSheet("")
        self.grilla_19_5.setObjectName("grilla_19_5")
        self.gridLayout.addWidget(self.grilla_19_5, 0, 5, 1, 1)
        self.grilla_1_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_1_3.setStyleSheet("")
        self.grilla_1_3.setObjectName("grilla_1_3")
        self.gridLayout.addWidget(self.grilla_1_3, 18, 3, 1, 1)
        self.grilla_2_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_2_3.setStyleSheet("")
        self.grilla_2_3.setObjectName("grilla_2_3")
        self.gridLayout.addWidget(self.grilla_2_3, 17, 3, 1, 1)
        self.grilla_12_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_12_0.setStyleSheet("")
        self.grilla_12_0.setObjectName("grilla_12_0")
        self.gridLayout.addWidget(self.grilla_12_0, 7, 0, 1, 1)
        self.grilla_13_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_13_7.setStyleSheet("")
        self.grilla_13_7.setObjectName("grilla_13_7")
        self.gridLayout.addWidget(self.grilla_13_7, 6, 7, 1, 1)
        self.grilla_6_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_6_0.setStyleSheet("")
        self.grilla_6_0.setObjectName("grilla_6_0")
        self.gridLayout.addWidget(self.grilla_6_0, 13, 0, 1, 1)
        self.grilla_17_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_17_7.setStyleSheet("")
        self.grilla_17_7.setObjectName("grilla_17_7")
        self.gridLayout.addWidget(self.grilla_17_7, 2, 7, 1, 1)
        self.grilla_3_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_3_3.setStyleSheet("")
        self.grilla_3_3.setObjectName("grilla_3_3")
        self.gridLayout.addWidget(self.grilla_3_3, 16, 3, 1, 1)
        self.grilla_13_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_13_1.setStyleSheet("")
        self.grilla_13_1.setObjectName("grilla_13_1")
        self.gridLayout.addWidget(self.grilla_13_1, 6, 1, 1, 1)
        self.grilla_0_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_0_0.setStyleSheet("")
        self.grilla_0_0.setObjectName("grilla_0_0")
        self.gridLayout.addWidget(self.grilla_0_0, 19, 0, 1, 1)
        self.grilla_7_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_7_0.setStyleSheet("")
        self.grilla_7_0.setObjectName("grilla_7_0")
        self.gridLayout.addWidget(self.grilla_7_0, 12, 0, 1, 1)
        self.grilla_3_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_3_0.setStyleSheet("")
        self.grilla_3_0.setObjectName("grilla_3_0")
        self.gridLayout.addWidget(self.grilla_3_0, 16, 0, 1, 1)
        self.grilla_13_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_13_0.setStyleSheet("")
        self.grilla_13_0.setObjectName("grilla_13_0")
        self.gridLayout.addWidget(self.grilla_13_0, 6, 0, 1, 1)
        self.grilla_12_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_12_9.setStyleSheet("")
        self.grilla_12_9.setObjectName("grilla_12_9")
        self.gridLayout.addWidget(self.grilla_12_9, 7, 9, 1, 1)
        self.grilla_12_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_12_5.setStyleSheet("")
        self.grilla_12_5.setObjectName("grilla_12_5")
        self.gridLayout.addWidget(self.grilla_12_5, 7, 5, 1, 1)
        self.grilla_13_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_13_8.setStyleSheet("")
        self.grilla_13_8.setObjectName("grilla_13_8")
        self.gridLayout.addWidget(self.grilla_13_8, 6, 8, 1, 1)
        self.grilla_9_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_9_0.setStyleSheet("")
        self.grilla_9_0.setObjectName("grilla_9_0")
        self.gridLayout.addWidget(self.grilla_9_0, 10, 0, 1, 1)
        self.grilla_9_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_9_9.setStyleSheet("")
        self.grilla_9_9.setObjectName("grilla_9_9")
        self.gridLayout.addWidget(self.grilla_9_9, 10, 9, 1, 1)
        self.grilla_10_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_10_8.setStyleSheet("")
        self.grilla_10_8.setObjectName("grilla_10_8")
        self.gridLayout.addWidget(self.grilla_10_8, 9, 8, 1, 1)
        self.grilla_5_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_5_9.setStyleSheet("")
        self.grilla_5_9.setObjectName("grilla_5_9")
        self.gridLayout.addWidget(self.grilla_5_9, 14, 9, 1, 1)
        self.grilla_8_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_8_9.setStyleSheet("")
        self.grilla_8_9.setObjectName("grilla_8_9")
        self.gridLayout.addWidget(self.grilla_8_9, 11, 9, 1, 1)
        self.grilla_2_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_2_0.setStyleSheet("")
        self.grilla_2_0.setObjectName("grilla_2_0")
        self.gridLayout.addWidget(self.grilla_2_0, 17, 0, 1, 1)
        self.grilla_6_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_6_9.setStyleSheet("")
        self.grilla_6_9.setObjectName("grilla_6_9")
        self.gridLayout.addWidget(self.grilla_6_9, 13, 9, 1, 1)
        self.grilla_13_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_13_6.setStyleSheet("")
        self.grilla_13_6.setObjectName("grilla_13_6")
        self.gridLayout.addWidget(self.grilla_13_6, 6, 6, 1, 1)
        self.grilla_12_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_12_8.setStyleSheet("")
        self.grilla_12_8.setObjectName("grilla_12_8")
        self.gridLayout.addWidget(self.grilla_12_8, 7, 8, 1, 1)
        self.grilla_10_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_10_4.setStyleSheet("")
        self.grilla_10_4.setObjectName("grilla_10_4")
        self.gridLayout.addWidget(self.grilla_10_4, 9, 4, 1, 1)
        self.grilla_0_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_0_9.setStyleSheet("")
        self.grilla_0_9.setObjectName("grilla_0_9")
        self.gridLayout.addWidget(self.grilla_0_9, 19, 9, 1, 1)
        self.grilla_4_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_4_0.setStyleSheet("")
        self.grilla_4_0.setObjectName("grilla_4_0")
        self.gridLayout.addWidget(self.grilla_4_0, 15, 0, 1, 1)
        self.grilla_3_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_3_9.setStyleSheet("")
        self.grilla_3_9.setObjectName("grilla_3_9")
        self.gridLayout.addWidget(self.grilla_3_9, 16, 9, 1, 1)
        self.grilla_7_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_7_9.setStyleSheet("")
        self.grilla_7_9.setObjectName("grilla_7_9")
        self.gridLayout.addWidget(self.grilla_7_9, 12, 9, 1, 1)
        self.grilla_1_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_1_9.setStyleSheet("")
        self.grilla_1_9.setObjectName("grilla_1_9")
        self.gridLayout.addWidget(self.grilla_1_9, 18, 9, 1, 1)
        self.grilla_5_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_5_0.setStyleSheet("")
        self.grilla_5_0.setObjectName("grilla_5_0")
        self.gridLayout.addWidget(self.grilla_5_0, 14, 0, 1, 1)
        self.grilla_2_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_2_9.setStyleSheet("")
        self.grilla_2_9.setObjectName("grilla_2_9")
        self.gridLayout.addWidget(self.grilla_2_9, 17, 9, 1, 1)
        self.grilla_0_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_0_5.setStyleSheet("")
        self.grilla_0_5.setObjectName("grilla_0_5")
        self.gridLayout.addWidget(self.grilla_0_5, 19, 5, 1, 1)
        self.grilla_19_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_19_1.setStyleSheet("")
        self.grilla_19_1.setObjectName("grilla_19_1")
        self.gridLayout.addWidget(self.grilla_19_1, 0, 1, 1, 1)
        self.grilla_14_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_14_8.setStyleSheet("")
        self.grilla_14_8.setObjectName("grilla_14_8")
        self.gridLayout.addWidget(self.grilla_14_8, 5, 8, 1, 1)
        self.grilla_17_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_17_4.setStyleSheet("")
        self.grilla_17_4.setObjectName("grilla_17_4")
        self.gridLayout.addWidget(self.grilla_17_4, 2, 4, 1, 1)
        self.grilla_16_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_16_4.setStyleSheet("")
        self.grilla_16_4.setObjectName("grilla_16_4")
        self.gridLayout.addWidget(self.grilla_16_4, 3, 4, 1, 1)
        self.grilla_17_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_17_8.setStyleSheet("")
        self.grilla_17_8.setObjectName("grilla_17_8")
        self.gridLayout.addWidget(self.grilla_17_8, 2, 8, 1, 1)
        self.grilla_19_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_19_9.setStyleSheet("")
        self.grilla_19_9.setObjectName("grilla_19_9")
        self.gridLayout.addWidget(self.grilla_19_9, 0, 9, 1, 1)
        self.grilla_12_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_12_4.setStyleSheet("")
        self.grilla_12_4.setObjectName("grilla_12_4")
        self.gridLayout.addWidget(self.grilla_12_4, 7, 4, 1, 1)
        self.grilla_0_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_0_4.setStyleSheet("")
        self.grilla_0_4.setObjectName("grilla_0_4")
        self.gridLayout.addWidget(self.grilla_0_4, 19, 4, 1, 1)
        self.grilla_18_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_18_1.setStyleSheet("")
        self.grilla_18_1.setObjectName("grilla_18_1")
        self.gridLayout.addWidget(self.grilla_18_1, 1, 1, 1, 1)
        self.grilla_17_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_17_1.setStyleSheet("")
        self.grilla_17_1.setObjectName("grilla_17_1")
        self.gridLayout.addWidget(self.grilla_17_1, 2, 1, 1, 1)
        self.grilla_11_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_11_8.setStyleSheet("")
        self.grilla_11_8.setObjectName("grilla_11_8")
        self.gridLayout.addWidget(self.grilla_11_8, 8, 8, 1, 1)
        self.grilla_11_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_11_1.setStyleSheet("")
        self.grilla_11_1.setObjectName("grilla_11_1")
        self.gridLayout.addWidget(self.grilla_11_1, 8, 1, 1, 1)
        self.grilla_16_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_16_2.setStyleSheet("")
        self.grilla_16_2.setObjectName("grilla_16_2")
        self.gridLayout.addWidget(self.grilla_16_2, 3, 2, 1, 1)
        self.grilla_16_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_16_3.setStyleSheet("")
        self.grilla_16_3.setObjectName("grilla_16_3")
        self.gridLayout.addWidget(self.grilla_16_3, 3, 3, 1, 1)
        self.grilla_4_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_4_1.setStyleSheet("")
        self.grilla_4_1.setObjectName("grilla_4_1")
        self.gridLayout.addWidget(self.grilla_4_1, 15, 1, 1, 1)
        self.grilla_12_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_12_7.setStyleSheet("")
        self.grilla_12_7.setObjectName("grilla_12_7")
        self.gridLayout.addWidget(self.grilla_12_7, 7, 7, 1, 1)
        self.grilla_18_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_18_0.setStyleSheet("")
        self.grilla_18_0.setObjectName("grilla_18_0")
        self.gridLayout.addWidget(self.grilla_18_0, 1, 0, 1, 1)
        self.grilla_4_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_4_9.setStyleSheet("")
        self.grilla_4_9.setObjectName("grilla_4_9")
        self.gridLayout.addWidget(self.grilla_4_9, 15, 9, 1, 1)
        self.grilla_19_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_19_6.setStyleSheet("")
        self.grilla_19_6.setObjectName("grilla_19_6")
        self.gridLayout.addWidget(self.grilla_19_6, 0, 6, 1, 1)
        self.grilla_19_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_19_7.setStyleSheet("")
        self.grilla_19_7.setObjectName("grilla_19_7")
        self.gridLayout.addWidget(self.grilla_19_7, 0, 7, 1, 1)
        self.grilla_10_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_10_9.setStyleSheet("")
        self.grilla_10_9.setObjectName("grilla_10_9")
        self.gridLayout.addWidget(self.grilla_10_9, 9, 9, 1, 1)
        self.grilla_19_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_19_3.setStyleSheet("")
        self.grilla_19_3.setObjectName("grilla_19_3")
        self.gridLayout.addWidget(self.grilla_19_3, 0, 3, 1, 1)
        self.grilla_19_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_19_4.setStyleSheet("")
        self.grilla_19_4.setObjectName("grilla_19_4")
        self.gridLayout.addWidget(self.grilla_19_4, 0, 4, 1, 1)
        self.grilla_18_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_18_2.setStyleSheet("")
        self.grilla_18_2.setObjectName("grilla_18_2")
        self.gridLayout.addWidget(self.grilla_18_2, 1, 2, 1, 1)
        self.grilla_19_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_19_8.setStyleSheet("")
        self.grilla_19_8.setObjectName("grilla_19_8")
        self.gridLayout.addWidget(self.grilla_19_8, 0, 8, 1, 1)
        self.grilla_13_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_13_3.setStyleSheet("")
        self.grilla_13_3.setObjectName("grilla_13_3")
        self.gridLayout.addWidget(self.grilla_13_3, 6, 3, 1, 1)
        self.grilla_15_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_15_1.setStyleSheet("")
        self.grilla_15_1.setObjectName("grilla_15_1")
        self.gridLayout.addWidget(self.grilla_15_1, 4, 1, 1, 1)
        self.grilla_18_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_18_3.setStyleSheet("")
        self.grilla_18_3.setObjectName("grilla_18_3")
        self.gridLayout.addWidget(self.grilla_18_3, 1, 3, 1, 1)
        self.grilla_0_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_0_3.setStyleSheet("")
        self.grilla_0_3.setObjectName("grilla_0_3")
        self.gridLayout.addWidget(self.grilla_0_3, 19, 3, 1, 1)
        self.grilla_10_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_10_0.setStyleSheet("")
        self.grilla_10_0.setObjectName("grilla_10_0")
        self.gridLayout.addWidget(self.grilla_10_0, 9, 0, 1, 1)
        self.grilla_5_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_5_3.setStyleSheet("")
        self.grilla_5_3.setObjectName("grilla_5_3")
        self.gridLayout.addWidget(self.grilla_5_3, 14, 3, 1, 1)
        self.grilla_15_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_15_0.setStyleSheet("")
        self.grilla_15_0.setObjectName("grilla_15_0")
        self.gridLayout.addWidget(self.grilla_15_0, 4, 0, 1, 1)
        self.grilla_11_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_11_0.setStyleSheet("")
        self.grilla_11_0.setObjectName("grilla_11_0")
        self.gridLayout.addWidget(self.grilla_11_0, 8, 0, 1, 1)
        self.grilla_9_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_9_3.setStyleSheet("")
        self.grilla_9_3.setObjectName("grilla_9_3")
        self.gridLayout.addWidget(self.grilla_9_3, 10, 3, 1, 1)
        self.grilla_16_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_16_8.setStyleSheet("")
        self.grilla_16_8.setObjectName("grilla_16_8")
        self.gridLayout.addWidget(self.grilla_16_8, 3, 8, 1, 1)
        self.grilla_15_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_15_8.setStyleSheet("")
        self.grilla_15_8.setObjectName("grilla_15_8")
        self.gridLayout.addWidget(self.grilla_15_8, 4, 8, 1, 1)
        self.grilla_17_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_17_3.setStyleSheet("")
        self.grilla_17_3.setObjectName("grilla_17_3")
        self.gridLayout.addWidget(self.grilla_17_3, 2, 3, 1, 1)
        self.grilla_16_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_16_5.setStyleSheet("")
        self.grilla_16_5.setObjectName("grilla_16_5")
        self.gridLayout.addWidget(self.grilla_16_5, 3, 5, 1, 1)
        self.grilla_19_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_19_0.setStyleSheet("")
        self.grilla_19_0.setObjectName("grilla_19_0")
        self.gridLayout.addWidget(self.grilla_19_0, 0, 0, 1, 1)
        self.grilla_6_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_6_3.setStyleSheet("")
        self.grilla_6_3.setObjectName("grilla_6_3")
        self.gridLayout.addWidget(self.grilla_6_3, 13, 3, 1, 1)
        self.grilla_11_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_11_5.setStyleSheet("")
        self.grilla_11_5.setObjectName("grilla_11_5")
        self.gridLayout.addWidget(self.grilla_11_5, 8, 5, 1, 1)
        self.grilla_11_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_11_7.setStyleSheet("")
        self.grilla_11_7.setObjectName("grilla_11_7")
        self.gridLayout.addWidget(self.grilla_11_7, 8, 7, 1, 1)
        self.grilla_18_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_18_5.setStyleSheet("")
        self.grilla_18_5.setObjectName("grilla_18_5")
        self.gridLayout.addWidget(self.grilla_18_5, 1, 5, 1, 1)
        self.grilla_7_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_7_3.setStyleSheet("")
        self.grilla_7_3.setObjectName("grilla_7_3")
        self.gridLayout.addWidget(self.grilla_7_3, 12, 3, 1, 1)
        self.grilla_18_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_18_7.setStyleSheet("")
        self.grilla_18_7.setObjectName("grilla_18_7")
        self.gridLayout.addWidget(self.grilla_18_7, 1, 7, 1, 1)
        self.grilla_1_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_1_0.setStyleSheet("")
        self.grilla_1_0.setObjectName("grilla_1_0")
        self.gridLayout.addWidget(self.grilla_1_0, 18, 0, 1, 1)
        self.grilla_14_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grilla_14_4.setStyleSheet("")
        self.grilla_14_4.setObjectName("grilla_14_4")
        self.gridLayout.addWidget(self.grilla_14_4, 5, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 467, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.fondo.setText(_translate("MainWindow", "TextLabel"))
        self.borde_1.setText(_translate("MainWindow", "TextLabel"))
        self.borde_2.setText(_translate("MainWindow", "TextLabel"))
        self.borde_3.setText(_translate("MainWindow", "TextLabel"))
        self.borde_4.setText(_translate("MainWindow", "TextLabel"))
        self.logo_DCCTetis.setText(_translate("MainWindow", "LOGO"))
        self.nombre.setText(_translate("MainWindow", "Nombre:"))
        self.nombre_usuario.setText(_translate("MainWindow", "nombre"))
        self.nombre_3.setText(_translate("MainWindow", "Puntaje:"))
        self.puntaje_usuario.setText(_translate("MainWindow", "pte"))
        self.nombre_4.setText(_translate("MainWindow", "Puntaje más alto:"))
        self.puntaje_mas_alto.setText(_translate("MainWindow", "highscore"))
        self.grilla_3_6.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_7_6.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_6_6.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_2_4.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_4_4.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_6_4.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_7_4.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_3_4.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_5_8.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_9_8.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_9_2.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_13_9.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_3_8.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_8_8.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_1_8.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_1_5.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_4_2.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_0_8.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_10_7.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_7_8.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_1_1.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_0_1.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_6_5.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_14_7.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_14_9.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_17_0.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_8_0.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_13_2.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_8_7.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_11_4.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_18_6.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_11_2.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_14_5.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_16_0.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_12_1.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_11_3.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_18_9.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_16_6.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_9_4.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_12_2.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_6_1.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_15_4.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_12_3.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_10_1.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_7_1.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_8_1.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_5_1.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_8_6.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_9_1.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_15_3.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_3_1.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_2_1.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_9_7.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_7_5.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_0_6.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_10_5.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_4_8.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_6_8.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_5_5.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_2_2.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_3_2.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_8_4.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_6_2.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_5_7.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_2_6.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_8_2.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_2_7.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_9_6.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_3_7.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_7_7.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_1_7.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_5_6.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_15_2.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_10_2.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_4_5.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_10_6.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_4_6.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_2_8.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_2_5.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_3_5.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_5_2.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_9_5.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_0_7.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_4_3.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_8_3.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_1_2.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_6_7.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_7_2.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_10_3.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_13_4.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_4_7.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_13_5.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_12_6.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_14_6.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_14_3.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_17_2.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_17_6.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_16_1.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_15_5.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_15_7.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_14_1.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_14_0.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_18_4.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_11_6.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_17_9.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_16_7.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_16_9.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_1_6.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_15_6.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_8_5.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_17_5.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_5_4.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_18_8.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_11_9.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_15_9.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_19_2.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_0_2.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_1_4.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_14_2.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_19_5.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_1_3.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_2_3.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_12_0.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_13_7.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_6_0.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_17_7.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_3_3.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_13_1.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_0_0.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_7_0.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_3_0.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_13_0.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_12_9.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_12_5.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_13_8.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_9_0.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_9_9.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_10_8.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_5_9.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_8_9.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_2_0.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_6_9.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_13_6.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_12_8.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_10_4.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_0_9.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_4_0.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_3_9.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_7_9.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_1_9.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_5_0.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_2_9.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_0_5.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_19_1.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_14_8.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_17_4.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_16_4.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_17_8.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_19_9.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_12_4.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_0_4.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_18_1.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_17_1.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_11_8.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_11_1.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_16_2.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_16_3.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_4_1.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_12_7.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_18_0.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_4_9.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_19_6.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_19_7.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_10_9.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_19_3.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_19_4.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_18_2.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_19_8.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_13_3.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_15_1.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_18_3.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_0_3.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_10_0.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_5_3.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_15_0.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_11_0.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_9_3.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_16_8.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_15_8.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_17_3.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_16_5.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_19_0.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_6_3.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_11_5.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_11_7.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_18_5.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_7_3.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_18_7.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_1_0.setText(_translate("MainWindow", "TextLabel"))
        self.grilla_14_4.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
